import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
// import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>

        <div className="min-h-[80vh]">
        {children}
        </div>
           {/* <Footer/> */}
        </body>
    </html>
  );
}